name: 'Aikido vulnerability scanner'
description: 'This action triggers a scan in Aikido. It will throw an error if any new critical issues were found.'
author: 'Aikido Security'
inputs:
  secret-key:
    description: 'Secret key provided by Aikido'
    required: true
  fail-on-timeout:
    description: 'Whether or not the action should fail when the scan does not complete within 2 minutes.'
    required: false
    default: "true"
outputs:
  outcome:
    description: |
      'The outcome of the scan. This will return `SUCCESS` in case we managed to do a scan and no new critical issues were found.\n
      When we did not get results back in time, within 2 minutes, we will return a `TIMEOUT` status but not let the action fail. 
      In case we did detect a new critical issue, the action will fail and outcome will be `FAILED`'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: 'purple'
